# Generated by Django 6.0.2 on 2026-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
