# Generated by Django 6.0.2 on 2026-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default_game.png', upload_to='game_covers/', verbose_name='Постер'),
        ),
    ]
