# Generated by Django 6.0.2 on 2026-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_botknowledge_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botknowledge',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
